// Code generated by go-swagger; DO NOT EDIT.

package region

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRegionsHandlerFunc turns a function with the right signature into a get regions handler
type GetRegionsHandlerFunc func(GetRegionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRegionsHandlerFunc) Handle(params GetRegionsParams) middleware.Responder {
	return fn(params)
}

// GetRegionsHandler interface for that can handle valid get regions params
type GetRegionsHandler interface {
	Handle(GetRegionsParams) middleware.Responder
}

// NewGetRegions creates a new http.Handler for the get regions operation
func NewGetRegions(ctx *middleware.Context, handler GetRegionsHandler) *GetRegions {
	return &GetRegions{Context: ctx, Handler: handler}
}

/*GetRegions swagger:route GET /regions region getRegions

получение списка регионов

*/
type GetRegions struct {
	Context *middleware.Context
	Handler GetRegionsHandler
}

func (o *GetRegions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRegionsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
