// Code generated by go-swagger; DO NOT EDIT.

package university

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetUniversitiesHandlerFunc turns a function with the right signature into a get universities handler
type GetUniversitiesHandlerFunc func(GetUniversitiesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUniversitiesHandlerFunc) Handle(params GetUniversitiesParams) middleware.Responder {
	return fn(params)
}

// GetUniversitiesHandler interface for that can handle valid get universities params
type GetUniversitiesHandler interface {
	Handle(GetUniversitiesParams) middleware.Responder
}

// NewGetUniversities creates a new http.Handler for the get universities operation
func NewGetUniversities(ctx *middleware.Context, handler GetUniversitiesHandler) *GetUniversities {
	return &GetUniversities{Context: ctx, Handler: handler}
}

/*GetUniversities swagger:route GET /universities university getUniversities

Получить список университетов

*/
type GetUniversities struct {
	Context *middleware.Context
	Handler GetUniversitiesHandler
}

func (o *GetUniversities) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUniversitiesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
