// Code generated by go-swagger; DO NOT EDIT.

package university

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "univers/pkg/models"
)

// GetUniversityOKCode is the HTTP code returned for type GetUniversityOK
const GetUniversityOKCode int = 200

/*GetUniversityOK успешное получение информации

swagger:response getUniversityOK
*/
type GetUniversityOK struct {

	/*
	  In: Body
	*/
	Payload *models.University `json:"body,omitempty"`
}

// NewGetUniversityOK creates GetUniversityOK with default headers values
func NewGetUniversityOK() *GetUniversityOK {

	return &GetUniversityOK{}
}

// WithPayload adds the payload to the get university o k response
func (o *GetUniversityOK) WithPayload(payload *models.University) *GetUniversityOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get university o k response
func (o *GetUniversityOK) SetPayload(payload *models.University) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUniversityOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
