// Code generated by go-swagger; DO NOT EDIT.

package university

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PatchUniversityHandlerFunc turns a function with the right signature into a patch university handler
type PatchUniversityHandlerFunc func(PatchUniversityParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchUniversityHandlerFunc) Handle(params PatchUniversityParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PatchUniversityHandler interface for that can handle valid patch university params
type PatchUniversityHandler interface {
	Handle(PatchUniversityParams, interface{}) middleware.Responder
}

// NewPatchUniversity creates a new http.Handler for the patch university operation
func NewPatchUniversity(ctx *middleware.Context, handler PatchUniversityHandler) *PatchUniversity {
	return &PatchUniversity{Context: ctx, Handler: handler}
}

/*PatchUniversity swagger:route PATCH /universities/{university_id} university patchUniversity

обновить информацию об университете

*/
type PatchUniversity struct {
	Context *middleware.Context
	Handler PatchUniversityHandler
}

func (o *PatchUniversity) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchUniversityParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
