// Code generated by go-swagger; DO NOT EDIT.

package university

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostUniversityHandlerFunc turns a function with the right signature into a post university handler
type PostUniversityHandlerFunc func(PostUniversityParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUniversityHandlerFunc) Handle(params PostUniversityParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostUniversityHandler interface for that can handle valid post university params
type PostUniversityHandler interface {
	Handle(PostUniversityParams, interface{}) middleware.Responder
}

// NewPostUniversity creates a new http.Handler for the post university operation
func NewPostUniversity(ctx *middleware.Context, handler PostUniversityHandler) *PostUniversity {
	return &PostUniversity{Context: ctx, Handler: handler}
}

/*PostUniversity swagger:route POST /universities university postUniversity

добавить новый университет

*/
type PostUniversity struct {
	Context *middleware.Context
	Handler PostUniversityHandler
}

func (o *PostUniversity) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostUniversityParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
