// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetPingNoContentCode is the HTTP code returned for type GetPingNoContent
const GetPingNoContentCode int = 204

/*GetPingNoContent ok

swagger:response getPingNoContent
*/
type GetPingNoContent struct {
}

// NewGetPingNoContent creates GetPingNoContent with default headers values
func NewGetPingNoContent() *GetPingNoContent {

	return &GetPingNoContent{}
}

// WriteResponse to the client
func (o *GetPingNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}
