// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UniversityFacultiesItemsConditionsItems требование поступления на факультет
// swagger:model universityFacultiesItemsConditionsItems
type UniversityFacultiesItemsConditionsItems struct {

	// условие поступления на факультет
	// Required: true
	AdmissionCondition string `json:"admission_condition"`

	// идентификатор фкультета
	// Required: true
	FacultyID int64 `json:"faculty_id"`

	// идентификатор требования поступления на факультет
	// Required: true
	ID int64 `json:"id"`
}

// Validate validates this university faculties items conditions items
func (m *UniversityFacultiesItemsConditionsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdmissionCondition(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFacultyID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UniversityFacultiesItemsConditionsItems) validateAdmissionCondition(formats strfmt.Registry) error {

	if err := validate.RequiredString("admission_condition", "body", string(m.AdmissionCondition)); err != nil {
		return err
	}

	return nil
}

func (m *UniversityFacultiesItemsConditionsItems) validateFacultyID(formats strfmt.Registry) error {

	if err := validate.Required("faculty_id", "body", int64(m.FacultyID)); err != nil {
		return err
	}

	return nil
}

func (m *UniversityFacultiesItemsConditionsItems) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", int64(m.ID)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UniversityFacultiesItemsConditionsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UniversityFacultiesItemsConditionsItems) UnmarshalBinary(b []byte) error {
	var res UniversityFacultiesItemsConditionsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
