// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UniversityUpdateDataFacultiesItems university update data faculties items
// swagger:model universityUpdateDataFacultiesItems
type UniversityUpdateDataFacultiesItems struct {

	// conditions
	// Required: true
	Conditions []*UniversityUpdateDataFacultiesItemsConditionsItems `json:"conditions"`

	// id
	ID int64 `json:"id,omitempty"`

	// name
	// Required: true
	Name string `json:"name"`

	// university id
	UniversityID int64 `json:"university_id,omitempty"`
}

// Validate validates this university update data faculties items
func (m *UniversityUpdateDataFacultiesItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConditions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UniversityUpdateDataFacultiesItems) validateConditions(formats strfmt.Registry) error {

	if err := validate.Required("conditions", "body", m.Conditions); err != nil {
		return err
	}

	for i := 0; i < len(m.Conditions); i++ {
		if swag.IsZero(m.Conditions[i]) { // not required
			continue
		}

		if m.Conditions[i] != nil {
			if err := m.Conditions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("conditions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *UniversityUpdateDataFacultiesItems) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UniversityUpdateDataFacultiesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UniversityUpdateDataFacultiesItems) UnmarshalBinary(b []byte) error {
	var res UniversityUpdateDataFacultiesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
