// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UniversityData данные университета
// swagger:model universityData
type UniversityData struct {

	// адресс университета
	// Required: true
	Address string `json:"address"`

	// faculties
	// Required: true
	Faculties []*UniversityDataFacultiesItems `json:"faculties"`

	// название университета
	// Required: true
	Name string `json:"name"`

	// rector
	// Required: true
	Rector *UniversityDataRector `json:"rector"`

	// region id
	// Required: true
	RegionID int64 `json:"region_id"`

	// профиль вуза
	// Required: true
	Shape string `json:"shape"`

	// статус вуза
	// Required: true
	// Enum: [state commercial]
	Status string `json:"status"`

	// кличество студентов
	// Required: true
	StudentNumber int64 `json:"student_number"`
}

// Validate validates this university data
func (m *UniversityData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFaculties(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRector(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRegionID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateShape(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStudentNumber(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UniversityData) validateAddress(formats strfmt.Registry) error {

	if err := validate.RequiredString("address", "body", string(m.Address)); err != nil {
		return err
	}

	return nil
}

func (m *UniversityData) validateFaculties(formats strfmt.Registry) error {

	if err := validate.Required("faculties", "body", m.Faculties); err != nil {
		return err
	}

	for i := 0; i < len(m.Faculties); i++ {
		if swag.IsZero(m.Faculties[i]) { // not required
			continue
		}

		if m.Faculties[i] != nil {
			if err := m.Faculties[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("faculties" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *UniversityData) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}

func (m *UniversityData) validateRector(formats strfmt.Registry) error {

	if err := validate.Required("rector", "body", m.Rector); err != nil {
		return err
	}

	if m.Rector != nil {
		if err := m.Rector.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rector")
			}
			return err
		}
	}

	return nil
}

func (m *UniversityData) validateRegionID(formats strfmt.Registry) error {

	if err := validate.Required("region_id", "body", int64(m.RegionID)); err != nil {
		return err
	}

	return nil
}

func (m *UniversityData) validateShape(formats strfmt.Registry) error {

	if err := validate.RequiredString("shape", "body", string(m.Shape)); err != nil {
		return err
	}

	return nil
}

var universityDataTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["state","commercial"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		universityDataTypeStatusPropEnum = append(universityDataTypeStatusPropEnum, v)
	}
}

const (

	// UniversityDataStatusState captures enum value "state"
	UniversityDataStatusState string = "state"

	// UniversityDataStatusCommercial captures enum value "commercial"
	UniversityDataStatusCommercial string = "commercial"
)

// prop value enum
func (m *UniversityData) validateStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, universityDataTypeStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *UniversityData) validateStatus(formats strfmt.Registry) error {

	if err := validate.RequiredString("status", "body", string(m.Status)); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

func (m *UniversityData) validateStudentNumber(formats strfmt.Registry) error {

	if err := validate.Required("student_number", "body", int64(m.StudentNumber)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UniversityData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UniversityData) UnmarshalBinary(b []byte) error {
	var res UniversityData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
